name: Generate test reports

on:
  workflow_run:
    workflows: [ 'Build and run tests' ]
    types:
      - completed

permissions:
  checks: write

jobs:
  net:
    name: .NET

    runs-on: ubuntu-latest

    steps:
      - name: Generate test report
        uses: dorny/test-reporter@v1
        with:
          name: .NET test report ($1)
          artifact: /net-test-results-(.*)/
          path: '**/*.trx'
          reporter: dotnet-trx
          list-tests: failed

  jvm:
    name: JVM

    runs-on: ubuntu-latest

    steps:
      - name: Generate test report
        uses: dorny/test-reporter@v1
        with:
          name: JVM test report ($1)
          artifact: /jvm-test-results-(.*)/
          path: '*.xml'
          reporter: java-junit
          list-tests: failed
